function [ddx,ddy,ddq] = autoGen_dynamics(q,u1,u2,m,g,d)
%AUTOGEN_DYNAMICS
%    [DDX,DDY,DDQ] = AUTOGEN_DYNAMICS(Q,U1,U2,M,G,D)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    12-May-2016 08:06:23

t2 = 1.0./m;
ddx = t2.*sin(q).*(u1+u2).*(-1.0./2.0);
if nargout > 1
    t3 = cos(q);
    ddy = t2.*(g.*m.*-2.0+t3.*u1+t3.*u2).*(1.0./2.0);
end
if nargout > 2
    ddq = (t2.*(u1-u2).*(-1.0./2.0))./d;
end
