function [X,dX,ddX,dddX,ddddX] = autoGen_getColPtState(t,xA,xB,dxA,dxB,ddxA,ddxB)
%AUTOGEN_GETCOLPTSTATE
%    [X,DX,DDX,DDDX,DDDDX] = AUTOGEN_GETCOLPTSTATE(T,XA,XB,DXA,DXB,DDXA,DDXB)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Mar-2016 17:24:14

t2 = t.^2;
t3 = t2.^2;
t4 = ddxA.*(1.0./1.6e1);
t5 = ddxB.*(1.0./1.6e1);
t6 = ddxA.*(1.0./8.0);
t7 = dxA.*(7.0./1.6e1);
t8 = dxB.*(7.0./1.6e1);
t9 = xA.*(1.5e1./1.6e1);
t10 = ddxB.*(1.0./8.0);
t11 = dxA.*(3.0./8.0);
t12 = dxB.*(-3.0./8.0)+t6+t10+t11;
t13 = dxA.*(5.0./8.0);
t14 = dxB.*(5.0./8.0);
t15 = xA.*(5.0./8.0);
t16 = dxA.*(3.0./1.6e1);
t17 = dxB.*(3.0./1.6e1);
t18 = xA.*(3.0./1.6e1);
t22 = xB.*(3.0./1.6e1);
t19 = t4-t5+t16+t17+t18-t22;
t20 = dxA.*(1.0./1.6e1);
t23 = dxB.*(1.0./1.6e1);
t21 = t4+t5+t20-t23;
X = dxA.*(5.0./1.6e1)-dxB.*(5.0./1.6e1)+t4+t5+xA.*(1.0./2.0)+xB.*(1.0./2.0)-t2.*t12+t3.*t21-t.*(t4-t5+t7+t8+t9-xB.*(1.5e1./1.6e1))+t.*t2.*(ddxB.*(-1.0./8.0)+t6+t13+t14+t15-xB.*(5.0./8.0))-t.*t3.*t19;
if nargout > 1
    t24 = t6-t10+t13+t14+t15-xB.*(5.0./8.0);
    dX = -t4+t5-t7-t8-t9+xB.*(1.5e1./1.6e1)-t.*t12.*2.0-t3.*t19.*5.0+t2.*t24.*3.0+t.*t2.*t21.*4.0;
end
if nargout > 2
    ddX = ddxA.*(-1.0./4.0)-ddxB.*(1.0./4.0)-dxA.*(3.0./4.0)+dxB.*(3.0./4.0)+t2.*t21.*1.2e1+t.*t24.*6.0-t.*t2.*t19.*2.0e1;
end
if nargout > 3
    dddX = ddxA.*(3.0./4.0)-ddxB.*(3.0./4.0)+dxA.*(1.5e1./4.0)+dxB.*(1.5e1./4.0)+xA.*(1.5e1./4.0)-xB.*(1.5e1./4.0)+t.*t21.*2.4e1-t2.*t19.*6.0e1;
end
if nargout > 4
    ddddX = ddxA.*(3.0./2.0)+ddxB.*(3.0./2.0)+dxA.*(3.0./2.0)-dxB.*(3.0./2.0)-t.*t19.*1.2e2;
end
