function [U,dU] = autoGen_getColPtControl(t,uA,uB,duA,duB)
%AUTOGEN_GETCOLPTCONTROL
%    [U,DU] = AUTOGEN_GETCOLPTCONTROL(T,UA,UB,DUA,DUB)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Mar-2016 17:24:15

t2 = duA.*(1.0./4.0);
t3 = duB.*(1.0./4.0);
t4 = t.^2;
t5 = uA.*(3.0./4.0);
t6 = t2-t3;
t7 = uA.*(1.0./4.0);
t8 = t2+t3+t7-uB.*(1.0./4.0);
U = duB.*(-1.0./4.0)+t2+uA.*(1.0./2.0)+uB.*(1.0./2.0)-t4.*t6-t.*(t2+t3+t5-uB.*(3.0./4.0))+t.*t4.*t8;
if nargout > 1
    dU = -t2-t3-t5+uB.*(3.0./4.0)-t.*t6.*2.0+t4.*t8.*3.0;
end
