function [C1,C2,C3,C4,C5,C6] = autoGen_stateSplineCoeffs(tA,tB,xA,xB,dxA,dxB,ddxA,ddxB)
%AUTOGEN_STATESPLINECOEFFS
%    [C1,C2,C3,C4,C5,C6] = AUTOGEN_STATESPLINECOEFFS(TA,TB,XA,XB,DXA,DXB,DDXA,DDXB)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Mar-2016 10:54:14

t2 = tA.^2;
t3 = tB.^2;
t4 = t2.^2;
t5 = t3.^2;
t6 = tA-tB;
t7 = 1.0./t6.^2;
t8 = t3.*tA.*3.0;
t11 = t2.*tB.*3.0;
t12 = t3.*tB;
t9 = t8-t11-t12+t2.*tA;
t10 = 1.0./t9;
C1 = t7.*t10.*(dxA.*t2.*t5.*1.0e1-dxB.*t3.*t4.*1.0e1-t5.*tA.*xA.*1.0e1-t4.*tA.*xB.*2.0+t5.*tB.*xA.*2.0+t4.*tB.*xB.*1.0e1-ddxA.*t2.*t5.*tA.*2.0-ddxB.*t2.*t5.*tA-ddxB.*t3.*t4.*tA+ddxA.*t2.*t5.*tB+ddxA.*t3.*t4.*tB+ddxB.*t3.*t4.*tB.*2.0-dxA.*t5.*tA.*tB.*2.0+dxB.*t4.*tA.*tB.*2.0-t2.*t3.*tA.*xB.*2.0e1+t2.*t3.*tB.*xA.*2.0e1-dxA.*t2.*t3.*tA.*tB.*8.0+dxB.*t2.*t3.*tA.*tB.*8.0).*(-1.0./2.0);
if nargout > 1
    C2 = t7.*t10.*(ddxA.*t2.*t5-ddxA.*t3.*t4.*3.0+ddxB.*t2.*t5.*3.0-ddxB.*t3.*t4-dxA.*t5.*tA.*1.0e1-dxB.*t4.*tA.*2.0+dxA.*t5.*tB.*2.0+dxB.*t4.*tB.*1.0e1-t2.*t3.*xA.*6.0e1+t2.*t3.*xB.*6.0e1+dxA.*t2.*t3.*tA.*2.4e1+dxB.*t2.*t3.*tA.*1.6e1-dxA.*t2.*t3.*tB.*1.6e1-dxB.*t2.*t3.*tB.*2.4e1-ddxA.*t5.*tA.*tB.*2.0+ddxB.*t4.*tA.*tB.*2.0+ddxA.*t2.*t3.*tA.*tB.*4.0-ddxB.*t2.*t3.*tA.*tB.*4.0).*(-1.0./2.0);
end
if nargout > 2
    C3 = t7.*t10.*(dxA.*t2.*t3.*1.2e1-dxB.*t2.*t3.*1.2e1-ddxA.*t5.*tA.*4.0+ddxB.*t4.*tA+ddxB.*t5.*tA.*3.0-ddxA.*t4.*tB.*3.0-ddxA.*t5.*tB+ddxB.*t4.*tB.*4.0-t3.*tA.*xA.*6.0e1-t2.*tB.*xA.*6.0e1+t3.*tA.*xB.*6.0e1+t2.*tB.*xB.*6.0e1-ddxB.*t2.*t3.*tA.*8.0+ddxA.*t2.*t3.*tB.*8.0+dxA.*t2.*tA.*tB.*2.4e1-dxA.*t3.*tA.*tB.*3.6e1+dxB.*t2.*tA.*tB.*3.6e1-dxB.*t3.*tA.*tB.*2.4e1).*(1.0./2.0);
end
if nargout > 3
    t13 = t2+t3-tA.*tB.*2.0;
    t14 = 1.0./t13;
    C4 = t10.*t14.*(ddxA.*t4+ddxA.*t5.*3.0-ddxB.*t4.*3.0-ddxB.*t5+t2.*xA.*2.0e1+t3.*xA.*2.0e1-t2.*xB.*2.0e1-t3.*xB.*2.0e1-ddxA.*t2.*t3.*8.0+ddxB.*t2.*t3.*8.0-dxA.*t2.*tA.*8.0+dxA.*t3.*tA.*2.8e1-dxB.*t2.*tA.*1.2e1+dxB.*t3.*tA.*3.2e1-dxA.*t2.*tB.*3.2e1+dxA.*t3.*tB.*1.2e1-dxB.*t2.*tB.*2.8e1+dxB.*t3.*tB.*8.0+tA.*tB.*xA.*8.0e1-tA.*tB.*xB.*8.0e1+ddxA.*t2.*tA.*tB.*4.0-ddxB.*t3.*tA.*tB.*4.0).*(1.0./2.0);
end
if nargout > 4
    C5 = t7.*t10.*(dxA.*t2.*1.4e1-dxA.*t3.*1.6e1+dxB.*t2.*1.6e1-dxB.*t3.*1.4e1-tA.*xA.*3.0e1+tA.*xB.*3.0e1-tB.*xA.*3.0e1+tB.*xB.*3.0e1-ddxA.*t2.*tA.*2.0+ddxA.*t3.*tA.*4.0+ddxB.*t2.*tA.*3.0-ddxB.*t3.*tA+ddxA.*t2.*tB-ddxA.*t3.*tB.*3.0-ddxB.*t2.*tB.*4.0+ddxB.*t3.*tB.*2.0+dxA.*tA.*tB.*2.0-dxB.*tA.*tB.*2.0).*(1.0./2.0);
end
if nargout > 5
    C6 = t10.*t14.*(xA.*1.2e1-xB.*1.2e1+ddxA.*t2+ddxA.*t3-ddxB.*t2-ddxB.*t3-dxA.*tA.*6.0-dxB.*tA.*6.0+dxA.*tB.*6.0+dxB.*tB.*6.0-ddxA.*tA.*tB.*2.0+ddxB.*tA.*tB.*2.0).*(1.0./2.0);
end
