function [C1,C2,C3,C4] = autoGen_controlSplineCoeffs(tA,tB,uA,uB,duA,duB)
%AUTOGEN_CONTROLSPLINECOEFFS
%    [C1,C2,C3,C4] = AUTOGEN_CONTROLSPLINECOEFFS(TA,TB,UA,UB,DUA,DUB)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Mar-2016 10:54:15

t2 = tA.^2;
t3 = tB.^2;
t4 = tA-tB;
t5 = 1.0./t4;
t8 = tA.*tB.*2.0;
t6 = t2+t3-t8;
t7 = 1.0./t6;
C1 = -t5.*t7.*(duA.*t2.*t3-duB.*t2.*t3-t3.*tA.*uA.*3.0-t2.*tA.*uB+t3.*tB.*uA+t2.*tB.*uB.*3.0-duA.*t3.*tA.*tB+duB.*t2.*tA.*tB);
if nargout > 1
    C2 = -t5.*t7.*(duA.*t3.*tA-duB.*t2.*tA+duB.*t3.*tA.*2.0-duA.*t2.*tB.*2.0+duA.*t3.*tB-duB.*t2.*tB+tA.*tB.*uA.*6.0-tA.*tB.*uB.*6.0);
end
if nargout > 2
    C3 = -t5.*t7.*(duA.*t2-duA.*t3.*2.0+duB.*t2.*2.0-duB.*t3-tA.*uA.*3.0+tA.*uB.*3.0-tB.*uA.*3.0+tB.*uB.*3.0+duA.*tA.*tB-duB.*tA.*tB);
end
if nargout > 3
    C4 = -t5.*t7.*(uA.*2.0-uB.*2.0-duA.*tA-duB.*tA+duA.*tB+duB.*tB);
end
