function [normAccel1,normAccel2] = autoGen_normBobAccel(q,dq,ddx,ddq,l)
%AUTOGEN_NORMBOBACCEL
%    [NORMACCEL1,NORMACCEL2] = AUTOGEN_NORMBOBACCEL(Q,DQ,DDX,DDQ,L)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Apr-2016 09:28:47

normAccel1 = ddx.^2;
if nargout > 1
    t3 = cos(q);
    t4 = dq.^2;
    t5 = sin(q);
    t2 = ddq.*l.*t5+l.*t3.*t4;
    t6 = ddx+ddq.*l.*t3-l.*t4.*t5;
    normAccel2 = t2.^2+t6.^2;
end
