function [normJerk1,normJerk2] = autoGen_normBobJerk(q,dq,ddq,dddx,dddq,l)
%AUTOGEN_NORMBOBJERK
%    [NORMJERK1,NORMJERK2] = AUTOGEN_NORMBOBJERK(Q,DQ,DDQ,DDDX,DDDQ,L)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Apr-2016 09:28:48

normJerk1 = dddx.^2;
if nargout > 1
    t2 = dq.^2;
    t3 = cos(q);
    t5 = sin(q);
    t4 = dddx+dddq.*l.*t3-ddq.*dq.*l.*t5.*3.0-dq.*l.*t2.*t3;
    t6 = dddq.*t5+ddq.*dq.*t3.*3.0-dq.*t2.*t5;
    normJerk2 = t4.^2+l.^2.*t6.^2;
end
