function [normSnap1,normSnap2] = autoGen_normBobSnap(q,dq,ddq,dddq,ddddx,ddddq,l)
%AUTOGEN_NORMBOBSNAP
%    [NORMSNAP1,NORMSNAP2] = AUTOGEN_NORMBOBSNAP(Q,DQ,DDQ,DDDQ,DDDDX,DDDDQ,L)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Apr-2016 09:28:48

normSnap1 = ddddx.^2;
if nargout > 1
    t2 = dq.^2;
    t3 = sin(q);
    t4 = cos(q);
    t6 = ddq.^2;
    t7 = t2.^2;
    t5 = ddddx+ddddq.*l.*t4-l.*t3.*t6.*3.0+l.*t3.*t7-dddq.*dq.*l.*t3.*4.0-ddq.*l.*t2.*t4.*6.0;
    t8 = ddddq.*t3+t4.*t6.*3.0-t4.*t7+dddq.*dq.*t4.*4.0-ddq.*t2.*t3.*6.0;
    normSnap2 = t5.^2+l.^2.*t8.^2;
end
