function [dddp1,dddp2] = autoGen_acrobotPosJerk(q1,q2,dq1,dq2,ddq1,ddq2,dddq1,dddq2,l1,l2)
%AUTOGEN_ACROBOTPOSJERK
%    [DDDP1,DDDP2] = AUTOGEN_ACROBOTPOSJERK(Q1,Q2,DQ1,DQ2,DDQ1,DDQ2,DDDQ1,DDDQ2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    06-Apr-2016 08:50:41

t2 = dq1.^2;
t3 = cos(q1);
t4 = sin(q1);
dddp1 = [-l1.*(-dddq1.*t3+ddq1.*dq1.*t4.*3.0+dq1.*t2.*t3);l1.*(dddq1.*t4+ddq1.*dq1.*t3.*3.0-dq1.*t2.*t4)];
if nargout > 1
    t5 = dq2.^2;
    t6 = cos(q2);
    t7 = sin(q2);
    dddp2 = [dddq1.*l1.*t3+dddq2.*l2.*t6-ddq1.*dq1.*l1.*t4.*3.0-ddq2.*dq2.*l2.*t7.*3.0-dq1.*l1.*t2.*t3-dq2.*l2.*t5.*t6;dddq1.*l1.*t4+dddq2.*l2.*t7+ddq1.*dq1.*l1.*t3.*3.0+ddq2.*dq2.*l2.*t6.*3.0-dq1.*l1.*t2.*t4-dq2.*l2.*t5.*t7];
end
