function [ddp1,ddp2] = autoGen_acrobotPosAccel(q1,q2,dq1,dq2,ddq1,ddq2,l1,l2)
%AUTOGEN_ACROBOTPOSACCEL
%    [DDP1,DDP2] = AUTOGEN_ACROBOTPOSACCEL(Q1,Q2,DQ1,DQ2,DDQ1,DDQ2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    06-Apr-2016 08:50:41

t2 = sin(q1);
t3 = dq1.^2;
t4 = cos(q1);
ddp1 = [l1.*(ddq1.*t4-t2.*t3);l1.*(ddq1.*t2+t3.*t4)];
if nargout > 1
    t5 = sin(q2);
    t6 = dq2.^2;
    t7 = cos(q2);
    ddp2 = [ddq1.*l1.*t4+ddq2.*l2.*t7-l1.*t2.*t3-l2.*t5.*t6;ddq1.*l1.*t2+ddq2.*l2.*t5+l1.*t3.*t4+l2.*t6.*t7];
end
