function [ddddp1,ddddp2] = autoGen_acrobotPosSnap(q1,q2,dq1,dq2,ddq1,ddq2,dddq1,dddq2,ddddq1,ddddq2,l1,l2)
%AUTOGEN_ACROBOTPOSSNAP
%    [DDDDP1,DDDDP2] = AUTOGEN_ACROBOTPOSSNAP(Q1,Q2,DQ1,DQ2,DDQ1,DDQ2,DDDQ1,DDDQ2,DDDDQ1,DDDDQ2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    06-Apr-2016 08:50:41

t2 = dq1.^2;
t3 = sin(q1);
t4 = cos(q1);
t5 = ddq1.^2;
t6 = t2.^2;
ddddp1 = [-l1.*(-ddddq1.*t4+t3.*t5.*3.0-t3.*t6+dddq1.*dq1.*t3.*4.0+ddq1.*t2.*t4.*6.0);l1.*(ddddq1.*t3+t4.*t5.*3.0-t4.*t6+dddq1.*dq1.*t4.*4.0-ddq1.*t2.*t3.*6.0)];
if nargout > 1
    t7 = dq2.^2;
    t8 = sin(q2);
    t9 = cos(q2);
    t10 = ddq2.^2;
    t11 = t7.^2;
    ddddp2 = [ddddq1.*l1.*t4+ddddq2.*l2.*t9-l1.*t3.*t5.*3.0+l1.*t3.*t6-l2.*t8.*t10.*3.0+l2.*t8.*t11-dddq1.*dq1.*l1.*t3.*4.0-dddq2.*dq2.*l2.*t8.*4.0-ddq1.*l1.*t2.*t4.*6.0-ddq2.*l2.*t7.*t9.*6.0;ddddq1.*l1.*t3+ddddq2.*l2.*t8+l1.*t4.*t5.*3.0-l1.*t4.*t6+l2.*t9.*t10.*3.0-l2.*t9.*t11+dddq1.*dq1.*l1.*t4.*4.0+dddq2.*dq2.*l2.*t9.*4.0-ddq1.*l1.*t2.*t3.*6.0-ddq2.*l2.*t7.*t8.*6.0];
end
